#
# Copyright (c) 2025 Huawei Technologies Co., Ltd. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# This file is a part of the AReaL project.
#

FROM quay.io/ascend/vllm-ascend:v0.14.0rc1-a3

# Update pip and install uv
RUN python3 -m pip install -U pip "setuptools>=77.0.3,<80" uv && \
    python3 -m pip cache purge

# Install AReaL dependencies
RUN --mount=type=cache,target=/root/.cache/uv \
    --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
    uv pip install -r pyproject.toml --system --extra npu --group dev

# Copy AReaL source code
COPY . /AReaL

# Install areal package in editable mode without dependencies
RUN uv pip install --no-deps -e /AReaL --system
